npm install express
npm install ejs
npm install cookie-parser
npm install express-session
npm install request-promise
npm install morgan
npm install mongoose
npm install mysql
npm install body-parser
npm install passport
npm install connect-flash
npm install passport-google-oauth
npm install passport-local
npm install passport-facebook
npm install bcrypt
